<a href="https://colab.research.google.com/github/park128/R_lecture/blob/main/day_0628.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 반복문 복습
- for loop and while loop

In [ ]:
for i in range(3):
  print("Hello World")
  print("안녕하세요")

Hello World
안녕하세요
Hello World
안녕하세요
Hello World
안녕하세요


In [ ]:
# "K" in "Kaggle"
if "K" == "a":
  print("출력이 되나요?")
else: 
  print("출력이 안된듯")


출력이 안된듯


In [ ]:
a = "Kaggle"

for i in a:
  print(i)
  if i == "a":
    break

K
a


- 리스트의 값이 존재
- 전체 총합 구하기


In [ ]:
numbers = [1, 2, 3, 4, 5]
sum = 0

for num in numbers:
  print("numbers: ", num)
  sum = sum + num 
  print("total:", sum)

print("----최종 결괏값----")
print(sum)

numbers:  1
total: 1
numbers:  2
total: 3
numbers:  3
total: 6
numbers:  4
total: 10
numbers:  5
total: 15
----최종 결괏값----
15


In [ ]:
fruits = ['apple', 'kiwi', 'mango']
newlist = []

# apple : a가 있나요? 있네요, newlist에 추가하세요. 
# kiwi : a가 있나요? 없네요. 그럼 넘어가요
# mango : a가 있나요? 있네요. newlist에 추가하세요. 
for fruit in fruits:
  print("조건문 밖 : ", fruit)
  if "a" in fruit:
    print("조건문 안쪽 : ", fruit)
    newlist.append(fruit)

print(newlist)

조건문 밖 :  apple
조건문 안쪽 :  apple
조건문 밖 :  kiwi
조건문 밖 :  mango
조건문 안쪽 :  mango
['apple', 'mango']


### While Loop

while문 : 분석할 때? 거의 쓸일이 없음


In [ ]:
i = 1
while i < 10: # 참일때만 반복문 코드가 돔
  # 코드
  print(i)
  i += 1 # 1씩 증감
  # i -= 1 # 1씩 감소

1
2
3
4
5
6
7
8
9


## 사용자 정의 함수
- 내가 필요에 의해 직접 함수를 작성


In [ ]:
def 함수명(param1, param2):
  # 코드 
  return None

In [ ]:
def add(a = 0, b = 1):
  # c = a + b 
  # return c
  return a + b

print(add(a = 5, b = 4))
print(add())

9
1


- 사칙연산 사용자 정의 함수 만들기
- 함수 문서화
  + 키워드 : Docstring

In [ ]:
def subtract(a, b):
  """a, b를 빼는 함수

  Parameters:
  a (int): int형 숫자 a가 입력
  
  b (int): int형 숫자 b가 입력

  Returns:
    int : 반환값
  """
  return a-b

print(subtract(a = 5, b = 10))
print(subtract.__doc__)

-5
a, b를 빼는 함수

  Parameters:
  a (int): int형 숫자 a가 입력
  
  b (int): int형 숫자 b가 입력

  Returns:
    int : 반환값

  


## NumPy
- 내장 모듈(=라이브러리=패키지) (X)
- 별도 라이브러리 설치 필요

In [ ]:
import numpy as np
print(np.__version__)

1.21.6


In [ ]:
temp = [1, 2, 3]
temp_array = np.array(temp) # 리스트에서 배열로 변환

print(type(temp))
print(type(temp_array))

<class 'list'>
<class 'numpy.ndarray'>


## 사칙연산

In [ ]:
math_score = [90, 80, 100, 60]
eng_score = [80, 90, 100, 50]

# math_score + eng_score
math_array = np.array(math_score)
eng_array = np.array(eng_score)

total = math_array + eng_array
print(total)
print(type(total))

[170 170 200 110]
<class 'numpy.ndarray'>


## 집계함수

In [ ]:
print(np.min(total))
print(np.max(total))
print(np.sum(total))

110
200
650


## 차원 확인
- 배열의 차원 확인 필요
- 

In [ ]:
# 1차원 배열 생성
temp_arr = np.array([1, 2, 3])
print(temp_arr.shape)
print(temp_arr.ndim)
print(temp_arr)

(3,)
1
[1 2 3]


In [ ]:
# 2차원 배열 생성
temp_arr = np.array([[1, 2, 3], [4, 5, 6]])
print(temp_arr.shape)
print(temp_arr.ndim)
print(temp_arr)

(2, 3)
2
[[1 2 3]
 [4 5 6]]


In [ ]:
# 3차원 배열 -> 이미지
temp_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(temp_arr.shape)
print(temp_arr.ndim)
print(temp_arr)

(2, 2, 3)
3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
(255, 255, 3)

## 배열 생성의 다양한 방법들
- 모두 0으로 채운다. 

In [ ]:
import numpy as np 
print(np.__version__)

1.21.6


In [ ]:
temp_arr = np.zeros((2, 3))
temp_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

- 모두 1로 채운다. 

In [ ]:
temp_arr = np.ones((2, 3))
temp_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

- 임의의 상수값으로 채운다. 

In [ ]:
temp_arr = np.full((3, 3), 100)
temp_arr

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

- 최소, 최대 숫자의 범위를 정해두고, 각 구간별로 값을 생성

In [ ]:
temp_arr = np.linspace(5, 10, 10)
temp_arr

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

- 반복문 시, 자주 등장하는 배열

In [ ]:
temp_arr = np.arange(1, 11, 1)
temp_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 난수 생성

In [ ]:
from numpy import random
x = random.rand()
print(x)

0.11621638529248979


In [ ]:
import numpy 
x = numpy.random.rand()
print(x)

0.3315584451465583


- 랜덤 정수값 추출

In [ ]:
from numpy import random 
# x = random.randint(100, size = (5))
x = random.randint(100, size = (3, 5))
print(x)
print(type(x))

[[88  2 19 78 13]
 [92 80 62 22 96]
 [66 71 89 62 76]]
<class 'numpy.ndarray'>


- 랜덤 배열, 실숫값 추출

In [ ]:
from numpy import random 
x = random.rand(2, 5)
print(x)
print(type(x))

[[0.06336531 0.34486775 0.66923826 0.31566607 0.84566463]
 [0.61713876 0.67541796 0.65161201 0.04912466 0.45433901]]
<class 'numpy.ndarray'>


## NumPy 사칙 연산

In [ ]:
import numpy as np
array_01 = np.array([1, 2, 3])
array_02 = np.array([10, 20, 30])

In [ ]:
# 덧셈
newArr = np.add(array_01, array_02)
print(newArr)

# 뺄셈
newArr = np.subtract(array_01, array_02)
print(newArr)

# 곱셈
newArr = np.multiply(array_01, array_02)
print(newArr)

# 나누기
newArr = np.divide(array_01, array_02)
print(newArr)

# 거듭제곱
array_01 = np.array([1, 2, 3])
array_02 = np.array([2, 4, 2])
newArr = np.power(array_01, array_02)
print(newArr)

[3 5 5]
[-1 -1  1]
[2 6 6]
[0.5        0.66666667 1.5       ]
[ 1 16  9]


## 소숫점 정렬
- 소숫점을 정렬하는 다양한 방법

In [ ]:
# 소숫점 제거 
import numpy as np
temp_arr = np.trunc([-1.23, 1.23])
print(temp_arr)

temp_arr = np.fix([-1.23, 1.23])
print(temp_arr)

[-1.  1.]
[-1.  1.]


In [ ]:
# 임의의 소숫점 자리에서 반올림
temp_arr = np.around([-1.234546123, 1.238791631], 5)
print(temp_arr)

[-1.23455  1.23879]


In [ ]:
# 소숫점 모두 내림
temp_arr = np.floor([-1.234546123, 1.238791631])
print(temp_arr)

[-2.  1.]


In [ ]:
# 소숫점 모두 올림
temp_arr = np.ceil([-1.234546123, 1.238791631])
print(temp_arr)

[-1.  2.]


## 조건식
- pandas 가공
- numpy
- 조건식
  + 하나의 조건식 (= np.where)
  + 다중 조건식


In [ ]:
temp_arr = np.arange(10)
temp_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 5보다 작으면 원 값 유지
# 5보다 크면 곱하기 10을 해줌

In [ ]:
# np.where(조건식, 참일 때, 거짓일 때)
np.where(temp_arr < 5, temp_arr, temp_arr * 10)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [ ]:
temp_arr = np.arange(10)
# temp_arr
cond_list   = [temp_arr > 5 , temp_arr < 2]
choice_list = [temp_arr  * 2, temp_arr + 100]

# np.select(조건식 리스트, 결괏값 리스트, default = )
np.select(cond_list, choice_list, default = temp_arr)

array([100, 101,   2,   3,   4,   5,  12,  14,  16,  18])

## Reshape
- 배열의 차원 또는 크기를 바꾼다. 
- 곱셈만 할줄 알면 끝. 

In [ ]:
import numpy as np 
temp_array = np.ones((3, 4))
print(temp_array.shape)
print(temp_array)

(3, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
after_reshape = temp_array.reshape(2, 2, 5)
print(after_reshape.shape)
print(after_reshape)

ValueError: ignored

In [ ]:
after_reshape = temp_array.reshape(7, -1)
print(after_reshape.shape)
print(after_reshape)

ValueError: ignored

# 브로드 캐스팅 

# pandas 튜토리얼

In [ ]:
import pandas as pd 
print(pd.__version__)

1.3.5


In [ ]:
temp_dict = {
    'col1' : [1, 2], 
    'col2' : [3, 4]
}

df = pd.DataFrame(temp_dict)
print(df)
print(type(df))

   col1  col2
0     1     3
1     2     4
<class 'pandas.core.frame.DataFrame'>


## 구글 드라이브 연동


In [ ]:
from google.colab import drive 
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
DATA_PATH = '/content/drive/MyDrive/Colab Notebooks/human_AI/Basic/Chapter 3. pandas/data/'
print(DATA_PATH + 'Lemonade2016.csv')

lemonade = pd.read_csv(DATA_PATH + 'Lemonade2016.csv')
# covid_df = pd.read_csv(DATA_PATH + 'owid-covid-data.csv')

lemonade.info() # str()

/content/drive/MyDrive/Colab Notebooks/human_AI/Basic/Chapter 3. pandas/data/Lemonade2016.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Date         31 non-null     object 
 1   Location     32 non-null     object 
 2   Lemon        32 non-null     int64  
 3   Orange       32 non-null     int64  
 4   Temperature  32 non-null     int64  
 5   Leaflets     31 non-null     float64
 6   Price        32 non-null     float64
dtypes: float64(2), int64(3), object(2)
memory usage: 1.9+ KB
