<a href="https://colab.research.google.com/github/park128/R_lecture/blob/main/day_0628.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
---
title: "Python 기초문법"
date: '2022-06-28'
---

# 반복문 복습
- for loop and while loop

In [ ]:
for i in range(1000):
  print("No : ", i+1)
  if i == 10:
    break
  print("Hello World")
  print("안녕하세요")

In [ ]:
a = "Kaggle"

for i in a:
  print(i)
  if i == "a":
    break

In [ ]:
"K" in "Kaggle"
if "K" == "a":
  print("출력이 되나요?")
else:
  print("출력이 안됨")

- 리스트의 값이 존재
- 전체 총합 구하기

In [ ]:
numbers =[1, 2, 3, 4, 5]
sum = 0

for num in numbers:
  print("numbers:" , num)
  sum = sum + num
  print("total:", sum)

print("----최종 결괏값-----")
print(sum)

In [ ]:
fruits = ['apple', 'kiwi', 'mango']
newlist = []

# apple : a가 있나요? 있네요. newlist에 추가하세요.
# kiwi : a가 있나요? 없네요. 그럼 넘어가요
# mango : a가 있나요? 있네요. newlist에 추가하세요
for fruit in fruits :
  print("조건문 밖 :" ,fruit)
  if "k" in fruit:
    print("조건문 안쪽:" , fruit)
    newlist.append(fruit)

print(newlist)

## While Loop

In [ ]:
i = 1
while i < 10: # 참일때만 반복문 코드가 돌게 됨
  # 코드
  i += 1 # 1씩 증감
  print(i)
  #i -= 1 # 1씩 감소

In [ ]:
i = 100
while i > 10: # 참일때만 반복문 코드가 돌게 됨
  # 코드
  #i += 1 # 1씩 증감
  i -= 1 # 1씩 감소
  print(i)

## 사용자 정의 함수
- 내가 필요에 의해 직접 함수를 작성

In [33]:
def 함수명(param1, param2):
  #코드
  return None

In [68]:
def add(a = 0, b = 1):
   c = a + b
   return c
  #return a + b
  

print(add(a = 5, b = 4))
print(add())

9
1


- 사칙연산 사용자 정의 함수 만들

In [72]:
def add(a, b):
  return a + b

print(add(4,5))

def abb(a, b):
  return a - b

print(abb(9,9))

def aff(a, b):
  return a * b

print(aff(7,3))

def car(a, b):
  return a / b

print(car(8,4))

9
0
21
2.0


In [76]:
def subtract(a, b):
  """
a, b를 빼는 함수

Parameters:
a (int) : int 형 숫자 a가 입력

b (int) : int 형 숫자 b가 dlqfur

Returns:
  int : 반환값

  """
  return a-b

print(subtract(a = 5, b = 10))

-5


## NumPy
- 내장 모듈(=라이브러리=패키지)
- 별도 라이브러리 설치 필요

In [78]:
import numpy as np
print(np.__version__)

1.21.6


In [80]:
temp = [1,2,3]
temp_array = np.array(temp) # 리스트에서 배열로 변환

print(type(temp))
print(type(temp_array))

<class 'list'>
<class 'numpy.ndarray'>


## 사칙연산

In [89]:
math_score = [90, 80, 100]
eng_score = [80, 90, 100]

# math_score + eng_score
math_score = np.array(math_score)
eng_score = np.array(eng_score)

total = math_array + eng_array
print(total)
print(type(total))


NameError: ignored

## 집계함수

In [88]:
print(np.min(total))
print(np.max(total))
print(np.sum(total))

NameError: ignored

## 차원 확인
- 배열의 차원 확인 필요
- 

In [ ]:
# 1차원 배열 생성
temp_arr = np.array([1, 2, 3])
print(temp_arr.shape)
print(temp_arr.ndim)
print(temp_arr)

In [ ]:
# 2차원 배열 생성
temp_arr = np.array([[1,2,3], [4,5,6]])
print(temp_arr.shape)
print(temp_arr.ndim)
print(temp_arr)

In [ ]:
# 3차원 배열 -> 이미지
temp_arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(temp_arr.shape)
print(temp_arr.ndim)
print(temp_arr)

## 배열 생성의 다양한 방법들
- 모두 0으로 채운다.


In [2]:
import numpy as np
print(np.__version__)

1.21.6


In [6]:
temp_arr = np.ones((2, 3))
temp_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

- 임의의 상수값으로 채운다.

In [8]:
temp_arr = np.full((3,3),100)
temp_arr

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

- 최소, 최대 숫자의 범위를 정해두고, 각 구간별로 값을 생성

In [9]:
temp_arr = np.linspace(5, 10, 10)
temp_arr

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

- 반복문 시, 자주 등장하는 배열

In [10]:
temp_arr = np.arange(1, 11, 1)
temp_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 난수 생성

In [17]:
from numpy import random
x = random.rand()
print(x)

0.6680686208892246


In [18]:
import numpy
x = numpy.random.rand()
print(x)

0.899287401044804


- 랜덤 정수값 추

In [26]:
from numpy import random
x = random.randint(100, size = (5))
print(x)
print(type(x))

[13 88 34  1 97]
<class 'numpy.ndarray'>


- 랜던 배열, 실숫값 추출

In [28]:
from numpy import random
x = random.rand(2, 5)
print(x)
print(type(x))

[[0.95995604 0.07848514 0.88021415 0.68953379 0.56988889]
 [0.65402798 0.30885682 0.13766482 0.17967603 0.7091518 ]]
<class 'numpy.ndarray'>


## NumPy 사칙 연산

In [30]:
import numpy as np
array_01 = np.array([1, 2, 3])
array_02 = np.array([10, 20, 30])


In [33]:
# 덧셈
newArr = np.add(array_01, array_02)
print(newArr)
# 뺄셈
newArr = np.subtract(array_01, array_02)
print(newArr)
# 곱셈
newArr = np.multiply(array_01, array_02)
print(newArr)
# 나눗셈
newArr = np.divide(array_01, array_02)
print(newArr)
# 거듭제곱
array_01 = np.array([1, 2, 3])
array_02 = np.array([2, 4, 2])
newArr = np.power(array_01, array_02)
print(newArr)

[3 6 5]
[-1 -2  1]
[2 8 6]
[0.5 0.5 1.5]
[ 1 16  9]


## 소숫점 정렬
- 소숫점을 정렬하는 다양한 방법

In [50]:
# 소숫점 제거
import numpy as np
temp_arr = np.trunc([-1.23, 1.23])
print(temp_arr)

temp_arr = np.fix[-1.23, 1.23])
print(temp_arr)

SyntaxError: ignored

In [36]:
# 임의의 소숫점 자리에서 반올림
temp_arr = np.around([-1.234546123, 1.238791631], 5)
print(temp_arr)

[-1.23455  1.23879]


In [ ]:
# 소숫점 모두 내림
temp_arr

- pan

In [37]:
temp_arr = np.arange(10)
temp_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 5보다 작으면 원 값 유지
# 5보다 크면 곱하기 10을 해줌

In [39]:
# np.where(조건식, 참일 때, 거짓일 때)
np.where(temp_arr < 5, temp_arr, temp_arr * 10)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [42]:
temp_arr = np.arange(10)
# temp_arr
cond_list = [temp_arr > 5, temp_arr <2]
choice_list = [temp_arr * 2, temp_arr +100]

# np.select(조건식 리스트, 결괏값 리스트, default =)
np.select(cond_list, choice_list, default = temp_arr)

array([100, 101,   2,   3,   4,   5,  12,  14,  16,  18])

## Reshape
- 배열의 차원 또는 크기를 바꾼다.
- 곱셈만 할줄 알면 끝.

In [47]:
import numpy as np
temp_array = np.ones((5, 4))
print(temp_array.shape)
print(temp_array)

(5, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [49]:
after_reshape = temp_array.reshape(2, 2, -1)
print(after_reshape.shape)
print(after_reshape)

(2, 2, 5)
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


# 브로드 캐스팅